### ISSUE TITLE
Coverage report is not generated

### ISSUE THREAD

**Issue by oscarfh** [AmadeusITGroup/sonar-coverage-evolution#6]
I got sonar-stash working (thanks a lot!) and now I would like to have coverage evolution.
I packaged and deployed the plugin, I can see the rules and I added it to my quality profile as "blocker"
I deleted changed something in a class and deleted the whole unit test class and made the pull request.

I get all the notifications about issues, I also get the overview comment from sonar-stash, but it doesn't contain the coverage information.

On the logs, there are no exceptions, but I am able to see that it is loaded:

```14:05:10.465 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] API compatibility mode is enabled on plugin Coverage Evolution [coverageevolution] (built with API lower than 5.2)```

```
14:05:10.563 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Plugins:
...
14:05:10.564 [DEBUG] [org.sonarqube.gradle.SonarQubeTask]   * Coverage Evolution 1.0.0-SNAPSHOT (coverageevolution)
```

The parameters I am sending are:

`-Dsonar.analysis.mode=preview -Dsonar.stash.repository=<repo> -Dsonar.stash.notification=true -Dsonar.stash.project=<project> -Dsonar.branch=master -Dsonar.stash.pullrequest.id=" + pullrequestId + " -Dsonar.stash.login=<login> -Dsonar.stash.password=<password> -x test -x javadoc -x findbugsMain -x findbugsTest --debug`

Any ideas what could be going wrong? I do not see any logging that could help me debug the code...

**Comment by t-8ch** [comment]
Hi @oscarfh, do you see some indication in the logs about "Coverage Evolution Sensor" being run?
You will also have to enable `-Dsonar.scanAllFiles`

**Comment by t-8ch** [comment]
It will be easier for testing the coverage stuff if you use the html report instead of sonar-stash.

**Comment by oscarfh** [comment]
No, there is no indication of Coverage Evolution Sensor in debug level. The only references to Coverage Evolution are the ones I pasted on my previous comment.

**Comment by t-8ch** [comment]
Which version of the scanner and SQ are you using?

**Comment by oscarfh** [comment]
I just found this entry:

> 15:07:11.716 [WARN] [org.sonarqube.gradle.SonarQubeTask] Not scanning all files, coverage features will be unreliable and will be disabled

I am checking to see if something was wrong with the parameter 

Sonarqube 6.4

**Comment by t-8ch** [comment]
So the sensor at least runs. There should be another status message from sonar about this.
Could you try with the setting?

**Comment by oscarfh** [comment]
I am getting that error " Unable to post a comment to ... Please enter a non-empty value less than 32768 characters"
I will try an workaround for this just to get it working.

**Comment by t-8ch** [comment]
Then you probably did not yet run an analysis in normal report mode.

**Comment by oscarfh** [comment]
I got it: because I deactivated a lot of tests in order to run my builds faster, I just had a huge list of items in the coverage list, which would cause the comment to be too big.
I had a quick fix and limited both issues list and coverage list to 10 and now it works.

I was thinking about limiting the size of each of these list by some value defined in the plugin configuration (one config to set eh limit of all table sizes in the overview comment) (I saw that there was another user who had a similar isso on the sonar-stash plugin). What do you think about this idea? If you think it is OK, I will make a pull request next week.

A second question:
We have a different structure inside our project: we have a repo and inside it we have multiple deployables. This would cause sonar-stash to never identify the change on the pull request diff view, showing the message "is not a new issue and so, not added to the report".
This would be caused because bitbucket would see the file as `folder1/folder2/folder3/file` while sonarqube would see it as `folder2/folder3/file`.
I made a change so `StashDiffReport.getType(..)` uses `if (diff.getPath().endsWith(path)) {` instead of  `if (Objects.equals(diff.getPath(), path)`
And Then I am using the path from the diff element in `org.sonar.plugins.stash.StashRequestFacade#postIssueComment` instead of the path from sonarqube.
If you approve this approach, I can also make a pull request.

**Comment by t-8ch** [comment]
@oscarfh  Now we are drifting into sonar-stash land :-)
For your first point: This is on the TODO list but not very far up.
For the second point: Please use: `-Dsonar.stash.repository.root`

**Comment by oscarfh** [comment]
I will try it tomorrow.
Is there anywhere I can see all the properties available?

BTW: I will try, but I do not think this property is going to solve my problem:
I have
< repo>/system/OneProject
< repo>/IntegrationTests/AnotherProject
< repo>/DatabaseTests/AThirdProject

So I do not have a fixed root in order to add to this property :(

**Comment by t-8ch** [comment]
@oscarfh This is mentioned in the README.
You should set this property to the path of `<repo>` in your example. This should do exactly what you want.

**Comment by t-8ch** [comment]
@oscarfh Can this be closed?

**Comment by oscarfh** [comment]
Sure, I completely forgot, thanks!
